data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Frequency"
public_key = "fa27ce4dc8947fecad01cb977342a3386d4ebe73680c5dd35b8c781f84826d48"

# [[chains]]
# name = "frequency"
# rpc_endpoint = "wss://collator1.frequency.xyz"
# color = "#4B64FF"
# testnet = false
#
# [chains.github_release]
# owner = "LibertyDSNP"
# repo = "frequency"
# genesis_hash = "0x055dccdb090bf02dce7661ea4a15406b8de6e1c92209ed928feba5ba1ee85387"

[[chains]]
vanity_name = "Frequency Rococo"
name = "frequency-rococo"
rpc_endpoint = "wss://frequency-seal.liberti.social:9944"
color = "#4B64FF"
testnet = true

[chains.github_release]
owner = "LibertyDSNP"
repo = "frequency"
genesis_hash = "0x2e4c812c20a86dc98692b6cba8ae6de21ccfb1c4303b5c166f68ccfa3117fdc9"
