data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Frequency"
public_key = "4402e2896c0aa61006b223f7f9b5e3703080c2f172642fd0c43de9892df76d79"

# [[chains]]
# name = "frequency"
# rpc_endpoint = "wss://collator1.frequency.xyz"
# color = "#4B64FF"
# testnet = false
#
# [chains.github_release]
# owner = "LibertyDSNP"
# repo = "frequency"
# genesis_hash = "0x055dccdb090bf02dce7661ea4a15406b8de6e1c92209ed928feba5ba1ee85387"
#

[[chains]]
vanity_name = "Frequency Rococo"
name = "frequency-rococo"
rpc_endpoint = "wss://rpc.rococo.frequency.xyz/"
color = "#4B64FF"
testnet = true

[chains.github_release]
owner = "LibertyDSNP"
repo = "frequency"
genesis_hash = "0x0c33dfffa907de5683ae21cc6b4af899b5c4de83f3794ed75b2dc74e1b088e72"
