data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Frequency"
public_key = "1KvbLQgGkCsj8JpT1ekXstHvtDQLs75vkBTXhTawyWLGdjF"

[[chains]]
name = "Frequency"
rpc_endpoint = " wss://rpc.frequency.xyz"
color = "#e6007a"

[chains.github_release]
owner = "LibertyDSNP"
repo = "frequency"
genesis_hash = "??"

[[chains]]
name = "Frequency Rococo"
rpc_endpoint = " wss://rococo-rpc.frequency.xyz"
color = "#000000"

[chains.github_release]
owner = "LibertyDSNP"
repo = "frequency"
genesis_hash = "0x055dccdb090bf02dce7661ea4a15406b8de6e1c92209ed928feba5ba1ee85387"

