data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Frequency"
public_key = "4402e2896c0aa61006b223f7f9b5e3703080c2f172642fd0c43de9892df76d79"

[[chains]]
vanity_name = "Frequency"
name = "frequency"
rpc_endpoint = "wss://1.rpc.frequency.xyz"
color = "#4B64FF"
testnet = false

[chains.github_release]
owner = "LibertyDSNP"
repo = "frequency"
genesis_hash = "0x4a587bf17a404e3572747add7aab7bbe56e805a5479c6c436f07f36fcc8d3ae1"

[[chains]]
vanity_name = "Frequency Testnet"
name = "frequency-testnet"
rpc_endpoint = "wss://rpc.rococo.frequency.xyz"
color = "#29FD47"
testnet = true

[chains.github_release]
owner = "LibertyDSNP"
repo = "frequency"
genesis_hash = "0x0c33dfffa907de5683ae21cc6b4af899b5c4de83f3794ed75b2dc74e1b088e72"
