data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Frequency"
public_key = "1KvbLQgGkCsj8JpT1ekXstHvtDQLs75vkBTXhTawyWLGdjF"

# [[chains]]
# name = "frequency"
# rpc_endpoint = "wss://collator1.frequency.xyz"
# color = "#4B64FF"
# icon = "https://raw.githubusercontent.com/LibertyDSNP/metadata-portal/main/public/FRQCY-Circle-Black.svg"
# testnet = false
#
# [chains.github_release]
# owner = "LibertyDSNP"
# repo = "frequency"
# genesis_hash = "0x055dccdb090bf02dce7661ea4a15406b8de6e1c92209ed928feba5ba1ee85387"


[[chains]]
name = "frequency-rococo"
rpc_endpoint = "wss://collator1.frequency.xyz"
color = "#4B64FF"
icon = "https://raw.githubusercontent.com/LibertyDSNP/metadata-portal/main/public/FRQCY-Circle-Black.svg"
testnet = true

[chains.github_release]
owner = "LibertyDSNP"
repo = "frequency"
genesis_hash = "0x055dccdb090bf02dce7661ea4a15406b8de6e1c92209ed928feba5ba1ee85387"
