runs:
  using: "composite"
  steps:
    - name: 🛠️Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y clang libclang-dev libopencv-dev
      shell: bash

    - name: 🔧 Install Rust (Stable)
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      shell: bash

    - name: 💾 Rust Cache
      uses: swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894
