# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CLI

on:
  pull_request:
    branches:
      - main
    paths:
      - "cli/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Install rust dependencies
        uses: ./.github/workflows/rust-install

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check

      - name: Cargo clippy
        run: cargo clippy -- -D warnings

      - name: Cargo test
        run: cargo test
