name: Deploy Main

on:
  push:
    branches:
     - main
    paths:
     - '**/*.yml'
     - '**/config.toml'
     - 'public/qr/**'

env:
  RUST_LOG: debug

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/rust-install

      - name: ⚙ Run verifier
        run: make verifier

      - name: ⚙ Run collector
        run: make collector

      - uses: ./.github/workflows/deploy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
