# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Main

on:
  workflow_dispatch: # via manual trigger
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/rust-install

      - name: ⚙ Run clean
        run: cargo clean

      - name: ⚙ Run verifier
        run: make verifier

      - name: ⚙ Run collector
        run: make collector

      - uses: ./.github/workflows/deploy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
