# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Verify

on:
  pull_request:
    branches:
      - main
    paths:
      - "public/qr/**"
      - "config.toml"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/rust-install

      - name: ⚙ Run clean
        run: cargo clean

      - name: ⚙ Run verifier
        run: cargo run --release -- verify
