name: Verify

on:
  pull_request:
    branches:
      - main
    paths:
      - 'public/qr/**'
      - 'config.toml'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/rust-install

      - name: ⚙ Build metadata-cli
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          command: build
          args: --release

      - name: ⚙ Run verifier
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          command: run
          args: --release -- verify
